SELECT COUNT(DISTINCT UGYFEL_FK) AS 'DARAB', MIN(LEN(UGYFEL_FK)) AS 'MIN', MAX(LEN(UGYFEL_FK)) AS 'MAX', AVG(LEN(UGYFEL_FK)) AS 'AVG'
FROM Foglalas
WHERE UGYFEL_FK IS NOT NULL

SELECT tipus, COUNT(*) AS 'darab' 
FROM (SELECT 
        CASE WHEN PATINDEX('%[0-9]%',UGYFEL_FK) > 0 THEN 'VAN'
            ELSE 'NINCS' 
            END AS tipus
        FROM Foglalas) rows
GROUP BY tipus

SELECT AVG(DATEDIFF(DAY,METTOL,MEDDIG)) AS 'ÁTLAGOS BÉRLÉS', 
FROM Foglalas
WHERE MEDDIG IS NOT NULL AND MEDDIG IS NOT NULL