SELECT COUNT(DISTINCT UGYFEL_FK) AS 'DARAB',
    MIN(LEN(UGYFEL_FK)) AS 'MIN',
    MAX(LEN(UGYFEL_FK)) AS 'MAX',
    AVG(LEN(UGYFEL_FK)) AS 'AVG',
    CAST(VAR(LEN(UGYFEL_FK)) AS NUMERIC(5,2)) AS 'VAR',
    CAST(STDEV(LEN(UGYFEL_FK)) AS NUMERIC(5,2))  AS 'STDEV'
FROM Foglalas
WHERE UGYFEL_FK IS NOT NULL

SELECT tipus, COUNT(*) AS 'DARAB', CAST(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER () AS NUMERIC(5,1)) AS 'SZÁZALÉK'
FROM (SELECT 
        CASE WHEN PATINDEX('%[0-9]%',UGYFEL_FK) > 0 THEN 'VAN'
            ELSE 'NINCS' 
            END AS tipus
        FROM Foglalas
        GROUP BY UGYFEL_FK) rows
GROUP BY tipus

SELECT top 10 UGYFEL_FK, COUNT(*) AS 'FOGLALÁSOK SZÁMA'
FROM Foglalas
GROUP BY UGYFEL_FK
ORDER BY COUNT(*) DESC

SELECT MONTH(METTOL) AS 'HÓNAP', COUNT(*) AS 'FOGLALÁSOK SZÁMA'
FROM Foglalas
WHERE MEDDIG IS NOT NULL
GROUP BY MONTH(METTOL)
ORDER BY MONTH(METTOL)

SELECT SZOBA_FK AS 'SZOBA',SUM(DATEDIFF(DAY,METTOL,MEDDIG)) AS 'NAPOK'
FROM Foglalas 
GROUP BY SZOBA_FK
ORDER BY SZOBA_FK


SELECT GYEREKES, [ÁTLAGOS BÉRLÉS],[MIN BÉRLÉS],[MAX BÉRLÉS]
FROM (SELECT 
        CASE WHEN GYERMEK_SZAM > 0 THEN 'IGEN'
            ELSE 'NEM' 
            END AS GYEREKES,
        AVG(DATEDIFF(DAY,METTOL,MEDDIG)) AS 'ÁTLAGOS BÉRLÉS',
        MIN(DATEDIFF(DAY,METTOL,MEDDIG)) AS 'MIN BÉRLÉS',
        MAX(DATEDIFF(DAY,METTOL,MEDDIG)) AS 'MAX BÉRLÉS'
        FROM Foglalas
        GROUP BY CASE WHEN GYERMEK_SZAM > 0 THEN 'IGEN'
            ELSE 'NEM' 
            END) rows
GROUP BY GYEREKES, [ÁTLAGOS BÉRLÉS],[MIN BÉRLÉS],[MAX BÉRLÉS]